# Generated by Django 3.2.5 on 2021-08-09 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rooms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_id', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_id', models.CharField(max_length=16)),
                ('nickname', models.CharField(max_length=255)),
                ('color', models.IntegerField()),
                ('eyes', models.IntegerField()),
                ('mouth', models.IntegerField()),
                ('leader', models.BooleanField()),
            ],
        ),
    ]
