# Generated by Django 3.2.4 on 2022-01-22 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rooms',
            fields=[
                ('room_id', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('reverse', models.BooleanField()),
                ('speed', models.DecimalField(decimal_places=2, max_digits=4)),
                ('rounds', models.IntegerField()),
                ('state', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_id', models.CharField(max_length=16)),
                ('nickname', models.CharField(max_length=255)),
                ('color', models.IntegerField()),
                ('eyes', models.IntegerField()),
                ('mouth', models.IntegerField()),
                ('leader', models.BooleanField()),
                ('uniqueID', models.CharField(max_length=16)),
                ('online', models.BooleanField()),
            ],
        ),
    ]
