# Generated by Django 3.2.5 on 2021-11-07 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rooms',
            name='id',
        ),
        migrations.AlterField(
            model_name='rooms',
            name='room_id',
            field=models.CharField(max_length=16, primary_key=True, serialize=False),
        ),
    ]
