# Generated by Django 3.2.4 on 2021-08-03 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='room_id',
            field=models.CharField(max_length=16),
        ),
    ]
