# Generated by Django 3.2.4 on 2021-09-12 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0003_auto_20210818_1917'),
    ]

    operations = [
        migrations.AddField(
            model_name='rooms',
            name='reverse',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rooms',
            name='rounds',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rooms',
            name='speed',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
