# Generated by Django 3.2.4 on 2021-09-19 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0004_auto_20210912_1841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rooms',
            name='rounds',
            field=models.DecimalField(decimal_places=4, max_digits=4),
        ),
        migrations.AlterField(
            model_name='rooms',
            name='speed',
            field=models.DecimalField(decimal_places=4, max_digits=4),
        ),
    ]
