# Generated by Django 3.2.4 on 2022-09-27 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0004_alter_chat_sender'),
    ]

    operations = [
        migrations.AddField(
            model_name='songs',
            name='randomId',
            field=models.CharField(default=1, max_length=16),
            preserve_default=False,
        ),
    ]
