# Generated by Django 3.2.4 on 2022-03-06 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0004_users_chosensongs'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='ready',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rooms',
            name='state',
            field=models.CharField(default='lobby', max_length=24),
        ),
    ]
