# Generated by Django 3.2.4 on 2021-09-19 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0005_auto_20210919_1936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rooms',
            name='rounds',
            field=models.IntegerField(),
        ),
    ]
