# Generated by Django 3.2.4 on 2022-09-27 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0005_songs_randomid'),
    ]

    operations = [
        migrations.AddField(
            model_name='songs',
            name='filelocation',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
