# Generated by Django 3.2.4 on 2022-10-04 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0006_songs_filelocation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='songs',
            name='randomId',
        ),
    ]
