# Generated by Django 3.2.4 on 2021-10-04 21:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0006_alter_rooms_rounds'),
    ]

    operations = [
        migrations.AddField(
            model_name='rooms',
            name='state',
            field=models.CharField(default=django.utils.timezone.now, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='users',
            name='uniqueID',
            field=models.CharField(default=django.utils.timezone.now, max_length=16),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rooms',
            name='speed',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
    ]
