# Generated by Django 3.2.4 on 2022-10-11 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0007_remove_songs_randomid'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='points',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
